// Generated by CoffeeScript 2.7.0
(function() {
  var aString, areYouHappy, cs0output, largeNumStr, largestNum, name, smallNumStr, smallestNum;

  name = "Phil";

  cs0output = document.getElementById("csoutput");

  cs0output.innerHTML = `Hello ${name}<br>`;

  aString = "I'm a string";

  if (typeof aString === 'string') {
    cs0output.insertAdjacentHTML('beforeend', 'aString is a String<br>');
  }

  largestNum = Number.MAX_VALUE;

  smallestNum = Number.MIN_VALUE;

  largeNumStr = `The largest number is ${largestNum}<br>`;

  smallNumStr = `The smalles number is ${smallestNum}<br>`;

  cs0output.insertAdjacentHTML('beforeend', largeNumStr + '<br>');

  cs0output.insertAdjacentHTML('beforeend', smallNumStr + '<br>');

  areYouHappy = false;

  if (typeof areYouHappy === 'boolean') {
    cs0output.insertAdjacentHTML('beforeend', 'areYouHappy is a Boolean<br>');
  }

  cs0output.insertAdjacentHTML('beforeend', `5 + 2 = ${5 + 2}<br>`);

  cs0output.insertAdjacentHTML('beforeend', `5 - 2 = ${5 - 2}<br>`);

  cs0output.insertAdjacentHTML('beforeend', `5 * 2 = ${5 * 2}<br>`);

  cs0output.insertAdjacentHTML('beforeend', `5 / 2 = ${5 / 2}<br>`);

  cs0output.insertAdjacentHTML('beforeend', `5 % 2 = ${5 % 2}<br>`);

}).call(this);
